### PR TITLE
Fix image name in tests

### PR DESCRIPTION
**Pull request by DifferentialOrange**
See #650 comments about closing the ticket.

I didn't forget about

- [x] Tests
- Changelog (change is minor)
- Documentation (not needed)

Follows up #650

### CODE REVIEW

**Comment by Totktonada** [comment]
Am I understand right: it does NOT change any behaviour, just to make the image name corresponding its purpose?

**Comment by DifferentialOrange** [comment]
> Am I understand right: it does NOT change any behaviour, just to make the image name corresponding its purpose?

Yes, it's cosmetic

**Review by Totktonada — APPROVED** [review]
Okay so. However I would suggest to avoid 'fix' word for changes, which does not change behaviour: it may be confusing.

**Review by LeonidVas — APPROVED** [review]

**Comment by LeonidVas** [comment]
> Okay so. However I would suggest to avoid 'fix' word for changes, which does not change behaviour: it may be confusing.

@DifferentialOrange prefers not to change the commit title.

**Pull request merged**
