### PR TITLE
ci: update to use go1.16

### PR DESCRIPTION
**Pull request by chenrui333**
relates to https://github.com/docker/go-docker/issues/19

### CODE REVIEW

**Comment by dokshina** [comment]
Hi! Sorry for long answering. Would it be OK for you if I rebase your patch and possibly add several changes since `go.mod` was changed in master?

**Comment by chenrui333** [comment]
no problem, let me rebase my PR.

**Comment by roopakv** [comment]
@dokshina would you be able to take a look at this and see if we can get it in and release a new version. This is currently blocking go1.16 from dropping on brew :) 

https://github.com/Homebrew/homebrew-core/pull/71289

**Comment by Bo98** [comment]
`go.sum` should probably be committed too. Go 1.16 no longer generates `go.sum` implicitly.

**Comment by dokshina** [comment]
@chenrui333, please, commit `go.sum`.

**Comment by dokshina** [comment]
@roopakv, yes, we will release a new version as soon as it's possible.

**Comment by dokshina** [comment]
Closed via #499, thanks!

**Pull request closed without merging**
